### PR TITLE
Added link to github page.

### PR DESCRIPTION
**Pull request by ghost**
I just added a link to the github page by clicking the octo-cat logo on the features sections. (It was annoying me)

### CODE REVIEW

**Comment by TropicSapling** [comment]
Possibly needs some css changes to prevent link highlights, I'll check it out later but for now I'll merge this :)

**Comment by ghost** [comment]
Oh wait; i can do that now if you like?

**Comment by TropicSapling** [comment]
I haven't checked if there even is any highlights yet though, but if you do notice any when running locally sure

**Comment by ghost** [comment]
Alright

**Comment by TropicSapling** [comment]
There didn't seem to be any highlights, [however I still had to do some modifications.](https://github.com/NN-Dev-Team/Nordic-Network/pull/135)

**Pull request merged**
