### PR TITLE
Removed `require("http-sync")`

### PR DESCRIPTION
**Pull request by ghost**
Removed `require("http-sync")` to go along with removing `http-sync`
from the `package.json` :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by TropicSapling** [comment]
Actually comment out the auto-updater instead

**Comment by ghost** [comment]
In `server.js`?

**Comment by TropicSapling** [comment]
yes

**Comment by ghost** [comment]
Oh ok will do :+1:

**Comment by TropicSapling** [comment]
Also revert the comment inside of auto-updater

**Comment by ghost** [comment]
Ok you can accept now

**Comment by ghost** [comment]
Okay wait

**Comment by ghost** [comment]
Ok you can accept now :+1:

**Pull request merged**
